### ISSUE TITLE
Updates to project.xml within this repository's README.md

### ISSUE THREAD

**Issue by jasonsturges** [openfl/away3d-samples#2]
Within this repository's [README.md](https://github.com/openfl/away3d-samples/blob/master/README.md), it looks like the project.xml example displayed has become dated.  For example, [in my discussion](http://community.openfl.org/t/away3d-html5-target-runtime-errors-with-lime/8926/2?u=jasonsturges) regarding issues with html5 target, it was suggested to remove the 'dom' haxedef flag from the project.xml as Away3d primarily targets WebGL.

    <project>
        <haxedef name="dom" if="html5" />
    </project>

Can this be reviewed, potentially removing the 'dom' haxedef?

**Comment by Greg209** [comment]
I've updated the README.md to reflect the current 'typical' project.xml. Thanks for pointing out the issue.
